spring:
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/news_db
    username: postgres
    password: postgres
    hikari:
      schema: news_schema
      connection-timeout: 10000